version: '2'

networks:
    prodnetwork:
        driver: bridge

services:
    nginx-proxy:
        image: ethiclab/buildmachine-nginx-proxy
        container_name: nginx-proxy
        ports:
            - "${PROXY_PORT}:80"
        networks:
            prodnetwork:
                aliases:
                    - web${ENV}.${DOMAIN}
                    - sonar${ENV}.${DOMAIN}
                    - nexus${ENV}.${DOMAIN}
                    - jenkins${ENV}.${DOMAIN}
                    - seleniumhub${ENV}.${DOMAIN}
                    - stash${ENV}.${DOMAIN}
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"

    web:
        image: nginx
        networks:
            - prodnetwork
        environment:
            - VIRTUAL_HOST=web${ENV}.${DOMAIN}
            - VIRTUAL_PORT=80

    jenkins:
        image: ethiclab/buildmachine-jenkins
        networks:
            - prodnetwork
        volumes:
            - "jenkinsvol:/var/jenkins_home"
        environment:
            - VIRTUAL_HOST=jenkins${ENV}.${DOMAIN}
            - VIRTUAL_PORT=8080

    nexus:
        image: sonatype/nexus
        networks:
            - prodnetwork
        volumes:
            - "nexusvol:/sonatype-work"
        environment:
            - VIRTUAL_HOST=nexus${ENV}.${DOMAIN}
            - VIRTUAL_PORT=8081

    sonar:
        image: ethiclab/buildmachine-sonar
        networks:
            - prodnetwork
        depends_on:
            - sonardb
        restart: "always"
        environment:
            - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
            - VIRTUAL_HOST=sonar${ENV}.${DOMAIN}
            - VIRTUAL_PORT=9000

    sonardb:
        image: postgres
        networks:
            - prodnetwork
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        volumes:
            - "sonardbvol:/var/lib/postgresql/data"

    seleniumhub:
        image: selenium/hub
        networks:
            - prodnetwork
        environment:
            - VIRTUAL_HOST=seleniumhub${ENV}.${DOMAIN}
            - VIRTUAL_PORT=4444

    nodeff:
        image: selenium/node-firefox
        networks:
            - prodnetwork
        environment:
            - HUB_PORT_4444_TCP_ADDR=seleniumhub
        depends_on:
            - seleniumhub

    nodechrome:
        image: selenium/node-chrome
        networks:
            - prodnetwork
        environment:
            - HUB_PORT_4444_TCP_ADDR=seleniumhub
        depends_on:
            - seleniumhub
    backup:
        image: ubuntu
        entrypoint: /bin/sh -c "while true; do sleep 1; done"
        networks:
            - prodnetwork
        volumes:
            - "jenkinsvol:/var/jenkins_home"
            - "nexusvol:/sonatype-work"
            - "sonardbvol:/var/lib/postgresql/data"
            - "stashvol:/var/atlassian/stash"
            - "stashdbvol:/var/lib/postgresql/data"
    stash:
        image: cptactionhank/atlassian-stash:3.4.1
        restart: "always"
        networks:
            - prodnetwork
        environment:
            - VIRTUAL_HOST=stash${ENV}.${DOMAIN}
            - VIRTUAL_PORT=7990
        depends_on:
            - stashdb
        volumes:
            - "stashvol:/var/atlassian/stash"
        
    stashdb:
        image: postgres:9.3
        networks:
            - prodnetwork
        environment:
            - POSTGRES_USER=stash
            - POSTGRES_PASSWORD=stash
        volumes:
            - "stashdbvol:/var/lib/postgresql/data"

volumes:
      jenkinsvol: {}
      sonardbvol: {}
      stashdbvol: {}
      stashvol: {}
      nexusvol: {}
